### ISSUE TITLE
Style Categorized : The generation of CartoCSS fails if there is data with special characters

### ISSUE THREAD

**Issue by dersteppenwolf** [gkudos/qgis-cartodb#31]
OS: Windows
Example Data: "Antonio Nariño"
Dataset: test_ideca_localidades

Generated Style:
#bogota_sitios_prostitucion_abril_2015[name="Antonio Nariﾃｱo"] {

**Comment by elesdoar** [comment]
CartoCSS for `test_ideca_localidades` on Ubuntu

```css
CartoCSS: /** Styles designed from QGISCartoDB Plugin */

#test_ideca_localidades {
  polygon-fill: #4be5d1;
  polygon-opacity: 1.0;
  polygon-comp-op: src-over;
  line-color: #000000;
  line-width: 1.0;
  line-opacity: 1.0;
  line-join: bevel;
  line-dasharray: 0;
}
#test_ideca_localidades[name="ANTONIO NARIÑO"] {
  polygon-fill: #f02495;
  polygon-opacity: 1.0;
  polygon-comp-op: src-over;
  line-color: #000000;
  line-width: 1.0;
  line-opacity: 1.0;
  line-join: bevel;
  line-dasharray: 0;
}
```
